[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#0d112aff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#454545ff"

# Color used for almost all text.
textColor = "#fff"

[client]
toolbarMode = "minimal"
